# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='date',
            field=models.CharField(default=b'2017-02-17 19:40', max_length=100),
        ),
    ]
