# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170217_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='contest',
            name='time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='date',
            field=models.CharField(default=b'2017-02-18 11:30', max_length=100),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
