# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170623_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='date',
            field=models.CharField(default=b'2017-06-23 10:07:23', max_length=100),
        ),
    ]
