# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170722_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='date',
            field=models.CharField(default=b'2017-07-22 21:55:23', max_length=100),
        ),
    ]
