# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=12)),
                ('session', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=200)),
                ('add', models.CharField(max_length=500)),
                ('phn', models.CharField(max_length=100)),
            ],
        ),
    ]
