# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='talat', max_length=100),
            preserve_default=False,
        ),
    ]
