# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170131_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='image_url',
            field=models.FileField(upload_to=b''),
        ),
    ]
