# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170204_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
