# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170204_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_of_fame',
            name='image_url',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall_of_fame',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
