# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170204_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='hall_of_fame',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recent',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
