# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170204_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_of_fame',
            name='coach',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
