# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_hall_of_fame_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='add',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phn',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
