# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170209_2034'),
    ]

    operations = [
        migrations.RenameModel('UserInfo', 'StudentProfile')
    ]
