# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170209_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='champion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halloffame',
            name='participated',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halloffame',
            name='top10',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halloffame',
            name='top5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
