# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_activationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
