# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_studentprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_add', models.CharField(blank=True, max_length=100)),
                ('permanent_add', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('about', models.CharField(blank=True, max_length=100)),
                ('working', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineContestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeforces', models.CharField(blank=True, max_length=100)),
                ('topcode', models.CharField(blank=True, max_length=100)),
                ('uva', models.CharField(blank=True, max_length=100)),
                ('hackerrank', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SustContestProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest1', models.IntegerField(default=0)),
                ('contest2', models.IntegerField(default=0)),
                ('contest3', models.IntegerField(default=0)),
                ('contest4', models.IntegerField(default=0)),
                ('contest5', models.IntegerField(default=0)),
                ('contest6', models.IntegerField(default=0)),
                ('contest7', models.IntegerField(default=0)),
                ('contest8', models.IntegerField(default=0)),
                ('contest9', models.IntegerField(default=0)),
                ('contest10', models.IntegerField(default=0)),
                ('contest11', models.IntegerField(default=0)),
                ('contest12', models.IntegerField(default=0)),
                ('contest13', models.IntegerField(default=0)),
                ('contest14', models.IntegerField(default=0)),
                ('contest15', models.IntegerField(default=0)),
                ('mx', models.IntegerField(default=0)),
                ('mn', models.IntegerField(default=0)),
                ('avg', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
