# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170221_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='propic',
            field=models.FileField(default=b'profile-icon.png', upload_to=b''),
        ),
    ]
