# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170222_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_url',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
