# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20170722_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recent',
            old_name='description',
            new_name='news',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='participated',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='top10',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='top5',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='title',
        ),
    ]
